#!/bin/bash

# Load resources
xrdb -merge .Xresources

# make Caps Lock another Control key
xmodmap -e "remove Lock = Caps_Lock"
xmodmap -e "add Control = Caps_Lock"

# start the emacs daemon
emacs --daemon

#################################################################
#### Deprecated : This jobs now handled by xmonad .##############
#################################################################

#Set up an icon tray
#trayer --edge top --align right --SetDockType true --SetPartialStrut true \
# --expand true --width 10 --transparent true --tint 0x191970 --height 12 &

# Set the background color
#xsetroot -solid midnightblue

#gajim &

#xscreensaver -no-splash &

#if [ -x /usr/bin/nm-applet ] ; then
#   nm-applet --sm-disable &
#fi

#if [ -x /usr/bin/gnome-power-manager ] ; then
#   sleep 3
#   gnome-power-manager &
#fi

#exec xmonad
