if [ "$TMUX" = "" ]; then tmux; fi

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="smt_rev"

# Aliases
alias zshconfig="mate ~/.zshrc"
alias ohmyzsh="mate ~/.oh-my-zsh"

alias ed="emacs --daemon"
alias e="emacsclient -c"
alias et="emacsclient -t"
alias vim="emacsclient -t"
alias vi="emacsclient -t"

alias ll="ls -l -h"
alias la="ls -a"
alias l="ls"
alias lla="ls -a -l"
alias lh="ls -l -h"
alias lah="ls -l -h -a"

alias grep="grep --color=auto"
alias gerp="grep --color=auto"

alias c="curl"
alias f="find"
alias g="git"
alias h="heroku"
alias m="more"
alias r="rgrep"
alias s="ssh"

# package management
alias sapti="sudo aptitude install"
alias saptr="sudo aptitude remove"
alias saptu="sudo aptitude update"
alias saptug="sudo aptitude upgrade"
alias saptsrc="apt-cache search"
alias sapts="apt-cache show"

# git
alias gst="git status"
alias gpl="git pull"
alias gps="git push"
alias gcam="git commit -am"
alias gbv="git branch -v"
alias gb="git branch"
alias gco="git checkout"
alias glt="git log -n 10"
alias gsu="git submodule update --init --recursive"


# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH=/home/rev/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
